import SideBar from '@/components/Layout/SideBar';
import React from 'react';
import Navigator from '@/components/Layout/elements/Navigator';
import Logo from '@/components/Layout/elements/Logo';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'YTMUSIC',
  description: 'Generated by create next app',
  icons: {
    icon: './youtube.png',
  },
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex flex-row h-full">
      <nav className="w-[240px] border-r-[1px] p-[20px]">
        <div className="p-[8px]">
          <Logo />
        </div>
        <div>
          <Navigator />
        </div>
      </nav>
      <div className="flex-1">{children}</div>
    </div>
  );
}
