import React from 'react';

import { Metadata } from 'next';
import { ThemeProvider } from '../../../../provider/ThemeProvider';
import PlayerWrapper from '@/components/player/PlayerWrapper';

export const metadata: Metadata = {
  title: 'YTMUSIC',
  description: 'Generated by create next app',
  icons: {
    icon: './youtube.png',
  },
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
      <div className="flex flex-row h-full ">
        <div className="w-full">{children}</div>
      </div>
    </ThemeProvider>
  );
}
