import React from 'react';

import { Metadata } from 'next';
import Header from '@/components/Layout/elements/Youtube_Header';
import SideBar from '@/components/Layout/SideBar';
import { Toaster } from '@/components/ui/sonner';
// export const metadata: Metadata = {
//   title: 'YTMUSIC',
//   description: 'Generated by create next app',
//   icons: {
//     icon: './youtube.png',
//   },
// };

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex flex-row h-full ">
      <SideBar />
      <div className="flex-1">
        <Header>{children}</Header>
      </div>
      <Toaster position="top-center" />
    </div>
  );
}
