import React from 'react';

import { Metadata } from 'next';
import { ThemeProvider } from '../../../../provider/ThemeProvider';
import ArkHeader from '@/components/Layout/Ark_elements/Header';

export const metadata: Metadata = {
  title: 'Mokokong',
  description: 'Generated by create next app',
  // icons: {
  //   icon: './youtube.png',
  // },
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
      <ArkHeader />
      {children}
    </ThemeProvider>
  );
}
