import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import StyledComponentsRegistry from '@/lib/registry';
import styles from './page.module.css';
import Header from '@/components/Layout/Header';
import { ThemeProvider } from '../../provider/ThemeProvider';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr" className={`${pretendard.variable}`}>
      <StyledComponentsRegistry>
        <body className={pretendard.className} style={{ overflowX: 'hidden' }}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <Header />
            <div className={styles.wrapper}>{children}</div>
          </ThemeProvider>
        </body>
      </StyledComponentsRegistry>
    </html>
  );
}
